### ISSUE TITLE
Upgrade to 5.4.17

### ISSUE THREAD

**Issue by n3npq** [OpenMandrivaAssociation/rpm#1]
OK, I have a procedure that will eventually permit an rpm upgrade in spite of 100's of patches.

0) CVS checkout on the rpm-5_4_15-release tag. Build and fix issues with newer prereqs.
1) Manually extract all the patches (and order of application) in a script. Apply, build, and fix.
2) Upgrade to the rpm-5_4_16-release tag. Fix merge conflicts and build.
3) Upgrade to the rpm-5_4_17-release tag. Fix merge conflicts and build.

I've done a preliminary pass and succeeded in building RPM to the point where I can't at least run tests to identify issues.

Q0: I see no point in carrying 300+ RPM patches separately, as its quite difficult to find WTF for any issue. Is a single coagulated patch acceptable or not?

Q1: Should I continue to rpm-5.4.18? There is nothing in rpm-5.4.18 that is going to hurt you afaik,
(and I can release a reference tarball for rpm-5.4.18 any time I wish). In fact, I believe OMA rpm-5.4.15 is based on a snapshot 5.4.15 tarball (but I could be wrong).

Q2: OMA is reverting changes from more than a decade ago, including
   * reading rpm v3 packaging (obsolete and unused since 2001)
   * using per-platform macros (abandoned in 2007)
   * changing header data type for epoch from uint32 -> int32 (2007) because POK didn't "like"
     the already implemented/supported functionality (2009)  to deprecate/remove EPOCH.
   * carrying lots of EVRD hacks (instead of fixes) that have been pointed out repeatedly (since 2011) and never prioritized because of "No time, release is more important." I think this ancient hysteria needs to go away or be fixed properly.

Q3: OMA (i.e. POK) have implemented bleeding edge functionality that has never been properly discussed. One change is the addition of 2 triggers for pre/post transactions that fundamentally changes the RPM state machine for no reason I understand. Are you using pre/post transaction triggers? Another change is loadable embedded interpreter modules, which has huge legacy implications if/when added to RPM. Both of these changes need wider public discussion and thought before consideration in RPM imho.

Q4: RPM5 upstream is carrying lots of #ifdef RPM_VENDOR_MANDRIVA code that is waiting to be pushed back to OMA largely because I cannot support code that isn't compiled/tested. Now is likely the time to sort out who is responsible for what changes. If I continue releasing upstream code with RPM_VENDOR_MANDRIVA patches, it creates a false hope that the code "works" and "compiles" and is "supported", and there are many examples of "Me too." enabling changes that are mostly reversions to development.

Q5: In order to build "officially", I need agreement on what build options are to be used. The de facto rpm.spec file isn't good enough because it depends on implicit AutoFu behavior detecting what is installed rather than explicit options that fail if a build prereq is missing. There are far too many options
to handle RPM functionality implicitly imho.

I need some indication of what is permitted before attempting another, more careful, upgrade pass to integrate.

**Comment by fedya** [comment]
> Are you using pre/post transaction triggers?
Yes.

> reading rpm v3 packaging (obsolete and unused since 2001)
Drop this crap

> using per-platform macros (abandoned in 2007)

We still use it like fedora or mageia.

> changing header data type for epoch from uint32 -> int32 (2007) because pPOK didn't "like"
I suggest to use an upstream, like you prefer.

> carrying lots of EVRD hacks
Sure

**Comment by n3npq** [comment]
Thanks for comments.

Re: Are you using pre/post transaction triggers?

OK, you are (likely, my guess) using posttranstrigger: pretranstrigger (and pretrans and pre) all have huge and obvious flaws when, say, installing into an empty chroot because there is nothing in an empty chroot to execute yet (and embedding is little used afaik). There are further complicated issues with dependency checks and ordering (through dependencies) that all triggers have, having tp do with pinning down the dynamic state where the trigger is executed.

If the goal is "functional package management", refactoring zillions of identical package scripts (like %pre -> %triggerprein, then additional triggers for %pretrans/%posttrans in the state machine might be needed. However, "functional package management" requires more than slots in the RPM state machine (to attempt a trigger replacement of a script), or using embedded scripting du jour (to avoid dependencies): you also need a trigger namespace that is more flexible and stronger abstraction than gobs/RE's on file paths.

Please point me at example usage cases so I can see WTF.

**Comment by n3npq** [comment]
Re: We still use it like fedora or mageia

OK. One of the nastier *MDV usage cases (circa 2011) was per-platform-includes (also known as multiplatfom iirc), with the arch as part  of the include path and RPM devel dependencies/packaging somehow expected to deal with the mess. Multiplatform (after discussion including pcpa in 2011) led to a decision to drop multiplatform, but I suspect that it may have persisted.

Is OMA still attempting multiplatfom installs (i.e. using %_arch to set up CFLAGS include paths)?

The main issue is whether you insist RPM be drop in all platforms out-of-the box. Maintain build configuration within the RPM package requires rpm to be rebuilt for every build configuration change. Fedora long ago started using rpmbuild-redhat-config (or whatever its called: I created the package) instead of continuing to use the associated per-cpu tarsal that was removed from rpm5 in 2007 (and is entirely unsupported: I wish to lose the legacy: any file present at rpm5.org is assumed "supported" and the reality is very different 10+y later no matter what Fedora/Mageia/PLD etc choose to continue using).

FWIW: Fedora (and RHEL/Centos) undertook making all include files platform-free, i.e. identical on all platforms, which is a better approach overall.

**Comment by Conan-Kudo** [comment]
@n3npq I completely agree that this stuff needs to be separated out. In Mageia, we have `rpm-mageia-setup`, which mimics the `redhat-rpm-config` package you created at Red Hat.

While I will not say I've gone through everything with a fine-toothed comb, I can say that at a glance, our [`rpm-mageia-setup`](http://svnweb.mageia.org/packages/cauldron/rpm-mageia-setup/current/SPECS/rpm-mageia-setup.spec?view=markup) (upstream project [rpm-setup](http://gitweb.mageia.org/software/rpm/rpm-setup/)) is more similar than different. Perhaps we could start from there as a good point to properly split out the OpenMandriva vendor configuration from upstream rpm and rid ourselves of some of the travesties in this package?

**Comment by n3npq** [comment]
Re: EPOCH deprecation

If you wish to deprecate EPOCH's distro-wide, then the approach should be (imho) distro-wide, not incremental by adding a "secret sauce" overloading of the sign bit in epoch's. The mechanism to ignore EPOCH's everywhere exists, and is easy to turn on/off while assessing removal of EPOCH everywhere. POK's incremental approach of adding negative EPOCH's as "deprecated" does not lead to removal.

**Comment by Conan-Kudo** [comment]
I don't particularly have any love for distepoch, and I'd rather it go away. I've not yet figured out a way that makes distepoch even sane, and it's certainly not for a lack of trying.

**Comment by n3npq** [comment]
Re: ... makes distepoch even sane ...

The big problem is mixtures of distepochs and other packaging: the mixture is worser than any single scheme. 

RPM5 can make DISTEPOCH disappear (i.e. be ignored) everywhere through configuration.

The other real problem with DISTEPOCH is the violation of the rule
           There are 2 '-' characters in every *.rpm file name that surround VERSION
which prevents (in a mixture of +/- DISTEPOCH named packages) writing simple
patterns to parse out NVRA from a list of package file names (DISTEPOCH adds a 3rd '-')

**Comment by berolinux** [comment]
On Monday, February 06, 2017 17:50 CET, Jeff Johnson <notifications@github.com> wrote: 
 
> OK, I have a procedure that will eventually permit an rpm upgrade in spite of 100's of patches.
> 
> 0) CVS checkout on the rpm-5_4_15-release tag. Build and fix issues with newer prereqs.
> 1) Manually extract all the patches (and order of application) in a script. Apply, build, and fix.
> 2) Upgrade to the rpm-5_4_16-release tag. Fix merge conflicts and build.
> 3) Upgrade to the rpm-5_4_17-release tag. Fix merge conflicts and build.

Sounds good...

> I've done a preliminary pass and succeeded in building RPM to the point where I can't at least run tests to identify issues.

Great.

> Q0: I see no point in carrying 300+ RPM patches separately, as its quite difficult to find WTF for any issue. Is a single coagulated patch acceptable or not?

The main purpose of keeping the patches split into chunks by context is that it makes it easier to drop ones that aren't needed anymore or that were simply a bad idea.
I think that's something we all want to do at some point...

> Q1: Should I continue to rpm-5.4.18?

Yes, please do -- no release imminent, so even if something were to break, there's enough time to fix it.

> Q2: OMA is reverting changes from more than a decade ago, including
>    * reading rpm v3 packaging (obsolete and unused since 2001)

I think that was about keeping LSB compliance. Personally I don't care, LSB has essentially made itself obsolete by sticking with requirements like rpm 3.x and qt 2.x, but it may have been a concern to Mandriva (the company), AFAIK they had some super-conservative customers (French government) where LSB compliance may have been a mandatory item on a checklist or something.

>    * using per-platform macros (abandoned in 2007)

I'd say they're still needed - they make crosscompiling RPMs ("rpmbuild -ba --target armv7hl whatever.spec") easier. Also, AFAIK Fedora and Mageia use them, and we like keeping some compatibility there - makes exchanging packages easier.

>    * changing header data type for epoch from uint32 -> int32 (2007) because pPOK didn't "like"
>      the already implemented/supported functionality (2009)  to deprecate/remove EPOCH.

AFAIK nothing ever really made use of that. Should be safe to drop those patches (and fix the 1 or 2 packages, if any, that might actually rely on it).

>    * carrying lots of EVRD hacks (instead of fixes) that have been pointed out repeatedly (since 2011) and never prioritized because of "No time, release is more important." I think this ancient hysteria needs to go away or be fixed properly.

Lack of time is still a concern, but essentially I think we agree that this should be fixed...

> Q3: OMA (i.e. POK) have implemented bleeding edge functionality that has never been properly discussed. One change is the addition of 2 triggers for pre/post transactions that fundamentally changes the RPM state machine for no reason I understand. Are you using pre/post transaction triggers? Another change is loadable embedded interpreter modules, which has huge legacy implications if/when added to RPM. Both of these changes need wider public discussion and thought before consideration in RPM imho.

I think a lot of this is used by the various bits that are done automatically these days (running ldconfig in post, install-info, ... just to name a few). Never looked too closely at how this is implemented.

Loadable embedded interpreter modules seem to be a good idea (so we can make use of them where they're useful without having dependencies of 100 interpreters in a core package we'd want even on an embedded system, rpm)

ttyl
bero

**Comment by Conan-Kudo** [comment]
> Loadable embedded interpreter modules seem to be a good idea (so we can make use of them where they're useful without having dependencies of 100 interpreters in a core package we'd want even on an embedded system, rpm)

They have some interesting and horrifying side effects, so I'm really wary of these.

**Comment by n3npq** [comment]
Re: Loadable embedded interpreter modules

You have chicken-egg problems with empty chroot's just like passwd.

And there are the further problems that almost every script language du jour depends on loadable modules, which changes a minor issue like loading an embedded interpreter into a hugely complex module loading dependency snarl in an empty chroot.

The main point I wish to point out is that "loadable" isn't as important as the discipline of choosing _SOME_ interpreter and minimizing the cost of using that interpreter (i.e. having RPM also provide some constant set of modules from a private load path).

If _SOME_ language == python, there is further work to do removing the rpm-peculiar namespace and the *ReadConfig() that is part of rpm-python (and POK has hacked around: there are better fixes available by splitting out into _init rather than hardwiring in C module code).

**Comment by Conan-Kudo** [comment]
We already have Lua, and from what I can tell, we don't really have the problems with Lua that we do with Python. Can't we just stick with that for now? Yeah, it's a bit on the weird side, but at least it has no chance of making rpm explode...

**Comment by n3npq** [comment]
LUA can make rpm explode as fast as python can.

Adding exception handling, and syscall wrapping, are necessary to do useful things while installing.

Note that RPM5 embeds both sed(1) (a pcre variant) and cp(1) independently of embedded interpreters. It would not be hard to add mkdir/rmdir/rm/... simple syscall wrappers independent of language scriptie du jour.

A third approach would be to build and distribute busybox or the *BSD utilities that are currently built with RPM in order to provide some dependency free set of executables that might be executed in an empty chroot, with RPM performing a mount -bind to import a private execution environment into an empty chroot.

**Comment by n3npq** [comment]
OK, I have some sense of what is needed.

There seems to be consensus on these items:

1) Get rid of RPMv3/LSB patches.
2) Spilit rpm configuration into a separate package, dropping cpu.os.macros.a and associated patches.
3) Drop patches for reverting a RPMTAG_EPOCH data type from uint32_t -> int32_t

Other issues that (imho) need further discussion will be split into separate issues, including

1) upgrading to rpm-5.4.18 (which involves eliminating --nosignature/--nodigest and RPM_I18NSTRING_TYPE)

2) Adding pre/post transaction triggers (I need examples of how used before going further).

3) Loadable interpreter modules (focussing on a single embedded language is needed).

4) Distepoch/epoch deprecation and package file naming (to eliminate the '-') which need to be done in concert with a "rebuild everything" in order to succeed.

Off to do the next lather-rinse-repeat upgrade. I will append the list of specific patches that are dropped in this issue.

**Comment by n3npq** [comment]
Script to apply patches to rpm-5.4.15 from CVS
[doit.sh.gz](https://github.com/OpenMandrivaAssociation/rpm/files/772250/doit.sh.gz)

**Comment by n3npq** [comment]
Notes on specific patch application failures before upgrading using CVS.

(Partial patch applications will be corrected on the way to rpm-5.4.17
[NOTES.gz](https://github.com/OpenMandrivaAssociation/rpm/files/772254/NOTES.gz)
)

**Comment by n3npq** [comment]
Below is the raw patch after applying OMA patches and then upgrading to rpm-5_4_17-release using CVS for reference.

Several patches that got in the way (again) like loadable embedded interpreters have been partially reverted. I have also resolved some issues by using rpm-5.4.18 files.

I will plot out other issues for discussion while cleaning up the raw patch as needed, an then provide a rpm-5.4.17 tar ball that might have a chance of compiling,

[oma+wdj-5.4.17.patch.0.gz](https://github.com/OpenMandrivaAssociation/rpm/files/772623/oma.wdj-5.4.17.patch.0.gz)

**Comment by tpgxyz** [comment]
@n3npq  This issue got obsoletes by latest one #9 ?
