### ISSUE TITLE
Upgrade to rpm-5.4.18: eliminating --nosignature/--nodigest and RPM_I18NSTRING_TYPE

### ISSUE THREAD

**Issue by n3npq** [OpenMandrivaAssociation/rpm#2]
rpm-5.4.18 (when released) will have these two important changes. This issue extends the discussion in issue #1.

1) Elimination of RPM_I18NSTRING_TYPE
    This data type is neither scalar nor vector, but rather both, based on context. There
    are also huge legacy/logistical impediments to using RPM_I18NSTRING_TYPE for anything except
    localization of summary/description/changelog.

     Most (PLD the notable exception) distros have migrated to either specspo or abandoning
     distribution of package localization entirely. rpm-5.4.18 is going to remove the code that
     handles RPM_I18NSTRING_TYPE entirely. A patch to re-add RPM_I18NSTRING_TYPE will be
     generated at the time of removal for the convenience of distros that insist on using
     RPM_I18NSTRING_TYPE, and rpm-5.4.18 will revert (as has been implemented for ~5y) the
     summary/description/changelog string values to the C locale and a RPM_STRING_TYPE value.

2) Elimination of --nosignature/--nodigest disablers
     Always verifying digest/signature when reading a package simplifies security audits.

     RPM5 has been automatically signing/verifying packages for ~5 years with no unsolved problems.
     All packages built by RPM5 are signed.

     Legacy support for "official" signatures continues exactly as before unchanged, with needs to
     distribute/import public keys in order to read *.rpm packages. The main difference is eliminating
     --nosignature/--nodigest disablers for unsigned (and unknown pubkey) failures. Repackaging,
     or resigning packages with a local pubkey is the recommended solution instead of adding
     --nosignature/--nodigest.

     A patch will be prepared when --nosignature/--nodigest is removed for the convenience of distros
     that insist on having --nosignature/--nodigest disablers.

**Comment by tpgxyz** [comment]
Elimination of RPM_I18NSTRING_TYPE
This is fine from my POV.


Elimination of --nosignature/--nodigest disablers
Above means, we need to check urpmi and other tools for these switches, as i have feeling they are used.

**Comment by n3npq** [comment]
Eliminating --nosignature/--nodigest will be API/ABI compatible: the bits can be set but will be ignored.
