### ISSUE TITLE
Loadable interpreter modules

### ISSUE THREAD

**Issue by n3npq** [OpenMandrivaAssociation/rpm#4]
In issue #1, the following (positive) reason(s) were given for loadable interpreter modules

> Loadable embedded interpreter modules seem to be a good idea (so we can make use of them where they're useful without having dependencies of 100 interpreters in a core package we'd want even on an embedded system, rpm)

 was presented.

Short answer (imho): maybe.

In general, dependencies on interpreter(s) can be avoided by embedding interpreter(s) in RPM. And there are certain programming problems that are easier to solve with better languages than POSIX shell scripts. Finally, moving interpreters which are seldom used into modules minimizes startup costs (by removing "bloat", whatever that might mean) of rpm executables/libraries. All easily understood.

However, serious use of an embedded interpreter while installing requires:
    a) a stand-alone executable for developing and reproducing problems
    b) additional "supported" embedded modules that cover reasonable packaging needs
Only RPM+LUA has had any serious attempts to satisfy both a) and b).

RPM also goes to some lengths to ensure that installations are "reliable". Supporting an embedded interpreter adds several new failure modes to RPM, including,
    a) buggy scripts that simply do not work (e.g. RPM5 can already check for syntax errors in POSIX scripts)
    b) working/tested interpreter scripts that do not work in all install contexts (triggers in particular)
    c) mixed execution state (signals vs exceptions) and data (embedded scripts may need wide
    access to current RPM transaction data) beyond what can be reasonably implemented by initializing
    the interpreter environment carefully, or by loading bindings.
RPM will be blamed for all installation failures no matter what.

But this issue is about "loadable interpreters", not "embedded interpreters". Loadable (as opposed to linked) interpreters adds dynamic elements to using rpm. If interpreters are packaged separately, then
the presence of the module is (usually) tracked with dependencies. Interpreter dependencies for modules are rather primitive and cannot fully track whether some (loadable embedded) interpreter is sufficiently "functional" to be used. It is quite common for interpreters to add dynamic logic to test for functionality and use if/when available. That run time dependency cannot be easily expressed with RPM dependencies, nor can those tests be easily (it is possible) mapped into RPM dependencies and/or run-time tests to ensure that a given rpm transaction has a reasonable chance of succeeding (again LUA has the most testing atm).

The convincing argument (to me) against _LOADING_ interpreter modules is that every attempt I can think of to increase rpm install transaction reliability is most easily avoided by _LINKING_ instead. 

There are many other issues (as hinted above) with embedded interpreters more important to solve than loading.

JMHO, YMMV.

Opinions? You can certainly attempt loadable interpreters as you wish even if we disagree.

**Comment by Conan-Kudo** [comment]
I've experimented with the feature a bit, and I'm mostly against it because of the unpredictable side-effects that it can cause.

At least for now, the linked in Lua stuff is more than sufficient for our purposes.

**Comment by n3npq** [comment]
You are against 1) embedded interpreters or 2) loadable interpreter modules? They are different (but somewhat related) issues.

**Comment by Conan-Kudo** [comment]
@n3npq I'm against loadable interpreter modules. I'm not completely certain about embedded ones. I think the embedded Lua interpreter is fine, but I'm not sure it's a great idea to have embedded Python or Perl ones.

**Comment by n3npq** [comment]
OK. I'm not sure (after seeing the patch) that loadable python was done correctly.

For hysterical reasons, the python module undertakes reading RPM configuration.

There are 2 modes for embedded (and loadable) operation:
   a) global (single shared state interpreter all invocations, like LUA was intended)
   b) isolated (multiple interpreters, one per invocation, for separate threads etc)

I do not understand why the patch (to read RPM configuration exactly once) was attempted if a global interpreter was instantiated: presumably multiple interpreters, or possibly an accidental recursion, was encountered.

Dunno, just guessing. Meanwhile python without exceptions is likely of little interest.

**Comment by n3npq** [comment]
The reasons for perl/python (and ruby/tcl/java/etc) interpreters is in slicing out interpreter du jour on the build system. See current +openssl -NSS discussion on rpm-mains. Same deal, just crypto rather than interpreters. Embedding interpreters can run dependency extraction or syntax checks, detecting flaws during build, not in QA or *ahem* on user machines with  associated bugzilla report overhead.

**Comment by proyvind** [comment]
Ideally I'd see a solution with a C-style OO objects being the only symbol dlsym()'ed when dlopen()'ing, where ie. something like say '%_interpreter_<name>', where for python the definition would be:
%_interpreter_<name>  %python_platlibdir/rpm/_rpm.so

Where from _rpm.so, it would dlsym() like a <name>_interpret struct/object for which all the relevant functinos would be members of.

IMO this would be the cleanest way with the least amount of maintenance required, with all responsibility for implementing the embedded interpreter support would be moved to individual interpreter bindings from which it would boot from.

WDYT?

**Comment by proyvind** [comment]
Btw. here's another very nice use of embedded interpreter, where the entire specfile is generated from as little as, while complying to packaging policies and layout which can easily be adapted to individual distros without the cruft from necessary to keep in the spec:
%{python:pyspec(<module>, <version>)

See generate.py :)
https://github.com/rpm-software-management/rpm/pull/96/commits/fc8a8ad0760dae11b789bf4935ae8873561762c9

**Comment by proyvind** [comment]
ps: other embeded interpretter support beyond lua oughta be confined to build time macros expanded in spec files and not be allowed to use for scriptlets.

Or if one would want to allow, one shoould require dealing additionally with things such as to deal with ie. dnf operating in same address space and only one global python interpreter with the need of dealing with avoid burning up...

**Comment by proyvind** [comment]
Note that the need for supporting multiple embedded interpreters is a definite MUSTHAVE if one would want build time spec generation for other languages such as ie. ruby etc. where it's just as easy to generate the spec files solely from metadata provided.


For oyher uses such as templating otherwise, one should really standardize on only allowing python and lua, or..?

**Comment by n3npq** [comment]
Re: https://github.com/rpm-software-management/rpm/pull/96/commits/fc8a8ad0760dae11b789bf4935ae8873561762c9

Generating a *.spec file is entirely off topic to "loadable interpreter modules", as is RFE's
for "Ideally I'd see a solution with a C-style OO objects ..."

There are numerous issues in designing a loadable module interface that is "portable" and "maintainable", not the least of which is a version number on the dlopen() API so that change is
at least possible without violating expectations of "legacy compatibility".

**Comment by n3npq** [comment]
Re: "other embeded interpretter support beyond lua oughta be confined to build time macros "

The issue ATM is what OMA expects from "loadable interpreter modules" so that a complicated
upgrade withy 300+ patches from rpm-5.4.15 -> rpm-5.4.17+ can be performed.

Other RFE's of bugs should be dealt with through other means than this specific issue.

**Comment by n3npq** [comment]
Re: "... supporting multiple embedded interpreters is a definite MUSTHAVE ... '"

Simply not true. rpm.org based distros are successfully creating per-interpreter packaging
without embedding any language except LUA.

Claiming MUSTHAVE without evidence helps nothing but your ego.

**Comment by tpgxyz** [comment]
I'd say that embedded support for LUA is enough. Others can be droped.

**Comment by n3npq** [comment]
Note that support for embedded interpreters involves subsidiary issues (like providing useful extensions through modules), handling signals/exceptions/errors (and shared state) gracefully, (for loading DSO's) designing a means to ensure that the interpreter can be loaded to run a script, and choosing whether the interpreter is global or isolated.

Its not just choosing whether "LUA is gud enuf".

Meanwhile this specific issue is tracking the OMA patch(s) to load interpreters, not all the rest.

**Comment by n3npq** [comment]
The issue of loadable interpreter modules (and embedded interpreters in RPM) is rather minor and easily re-added if/when desired.

So I have dropped the patch to simplify. I am also routinely dropping all changes to internal lua because rpm-5.4.17+ has a later version of lua which has been fully tested and scanned by coverity and -fsanitize=address. I'm sure that lua in rpm-5.4.17+ is better than what was in rpm-5.4.15+patches

**Comment by proyvind** [comment]
Worth noticing is that the existing implementation only actually implements support for using embedded intepreter during package build time, not available for use in scriptlets etc.

It's not intended to "compete" with lua, but rather for package templating for which lua isn't particularly suitable at all.
