### ISSUE TITLE
Distepoch/Epoch global changes

### ISSUE THREAD

**Issue by n3npq** [OpenMandrivaAssociation/rpm#5]
This issue continues the discussion from issue #1.

Q: Is a "rebuild everything" planned before the next OMA "official" release?

There are 2 issues that are best handled by coordinating with a "rebuild everything" event.

1) Eliminate all occurrences of RPMTAG_EPOCH
    With a "rebuild everything" event, it is feasible to refactor the existing currently used epoch out
    of packaging and into a subsidiary configuration file. I.e. RPM itself would ignore RPMTAG_EPOCH
    in all comparisons for rebuilt packages, and RPM itself, not *.rpm, would supply an epoch where
    needed in comparisons between rebuilt and older packages.

2) Consistent naming of *.rpm files that use RPMTAG_DISTEPOCH
     Last I checked (some years ago), RPMTAG_DISTEPOCH was used inconsistently in OMA packaging.
     There are 2 types of inconsistency:
      a) missing +DISTEPOCH with -DISTEPOCH *.rpm packages  (extra '-' in +DISTEPOCH  *.rpm files)
      b) (+DISTEPOCH only) mixtures of older and newer DISTEPOCH values (reported as "bugs")

     I am mostly concerned about inconsistency, but also concerned re deviation from RPM convention

> The last 2 '-' characters in a *.rpm file name SHOULD surround version.

**Comment by Conan-Kudo** [comment]
With eliminating `RPMTAG_EPOCH`, does that mean that the `Epoch` value in spec files would be completely ignored in favor of the distro-controlled one? Or does the `Epoch` value become additive to effectively have the same effect?

Is distepoch needed at all if we do global epoch stuff?

**Comment by proyvind** [comment]
distepoch is the least significant value in contrast to epoch being the most significant..

Changing the delimiter to ie. the virtually unused '+' in verrsion/release was the approach I was planning on implement to fix the parsing of NVRD from package filename..


I don't get why addresing distepoch issue and the unrelated epoch deprecation issue in the same issue opened up, they're not really related..

**Comment by n3npq** [comment]
Correction: D is the least significant comparison element (and E -s the most significant) depends on the configuration of
`# STEP 3: Configure the comparison order of the <E,V,T,R,D> tuple elements
%evr_tuple_order  EVR
`

The addition of (and particularly the mixture of +/- DISTEPoCH packaging) and extra '-' character prevents extracting VERSION form a list of package file names (we have had this conversation multiple times over the last 5+ years).

If you want '+' (or '.' or '@' or anything but '-') is a secondary conversation.

Adding an additional '-' character (and a mixture of +/- DISTEPOCH rpm file names) violates expectations and turns a simple *RE or glob into a hugely complex pattern matching cluster-fuck.

**Comment by n3npq** [comment]
Re: "... eliminating RPMTAG_EPOCH ..." (to proyvind)

Yes (but not in *.spec, run-time dependencies on _EVERY_  EVRD comparison through rpmlib while _INSTALLING_ can be changed for precedence or by ignoring).

By configuring (or permuting the {E,V,R,D} symbols) both precedence (and ignoring
undesired Distepoch as Unity did, or changing to prefer R over V as OpenPKG did, or entirely ignoring Epoch: as Chaos did) is possible.

`# STEP 3: Configure the comparison order of the <E,V,T,R,D> tuple elements
%evr_tuple_order  EVR
`

Your ignorance of the implementation that _YOU_ wanted 6+ years later is unforgivable. We have discussed this multiple times. Go do your homework please ...

**Comment by n3npq** [comment]
@Conan-Kudo: the mechanism for changing precedence or for ignoring Distepoch/Epoch is the common factor.

Meanwhile the policy (an expectations) is the issue. The mechanism for changing precedence
(or ignoring everywhere in existing packaging) for any of the {E,V,T,R,D} five tuple (T == twiddle in version) for all applications that choose to use the rpm lib API has been deployed/tested for ~8y
and is known to "work".

What policy issues OMA chooses to configure RPM is != mechanism supported by RPM5.

**Comment by n3npq** [comment]
From #openmadriva-cooker

* bero thinks we should do a mass build before the 4.0 release (but not before any 3.x releases) to make sure everything has been built w/ the right toolchain and all
