### ISSUE TITLE
Eliminate rpm-5.4.14-rpmdbchk.patch?

### ISSUE THREAD

**Issue by n3npq** [OpenMandrivaAssociation/rpm#6]
(split from issue #1)

Back in 2011, with highly charged political splits between the M&M (&R) distros, there was arguable justification for a rpmdbchk soft fuzzy blanket executable to satisfy angry lusers.

Not any more: there are very very few reported rpmdb problems, and even fewer where rpmdbchk might even help. I hear about most rpmdb problems rather quickly, and haven't heard an issue for several years.

Adding utilities that pretend to repair rpmdb "corruption" fixes the wrong problem because the utilities apply a bandaid to a superficial symptom rather than fixing (or at least diagnosing) the root cause for whatever problem is being reported.

And -- I claim after ~7y experience with the rpmdb  implementation @rpm5.org on multiple distros -- the implementation is quite good and there are better (and "officially" documented and supported "upstream") procedures to manage BerkeleyDB that are superior to rpmdbchk.c and its ilk.

If you absolutely MUST hug your soft fuzzy hysterical blanket, then split rpmdbchk out of rpm into a separate package. 

Drop rpm-5.4.14-rpmdbchk.patch(Y/n)?

Or create separate rpmdbchk package (y/N)?

**Comment by n3npq** [comment]
On #openmandriva-cooker, a separate package, not in RPM sources,  seemed to have the most consensus, though objections were vigorously raised.

**Comment by tpgxyz** [comment]
@n3npq  IMHO we should drop this rpmdbchk tool, as i have feeling that noting is using it at all.
