### ISSUE TITLE
Split all RPM configuration out of the rpm package?

### ISSUE THREAD

**Issue by n3npq** [OpenMandrivaAssociation/rpm#7]
(split from issue #1)

Because of the approach to upgrading 5.4.15 -> 5.4.17, I happen to be able to
provide objective statistics on the 300+ patches in OMA.

RPM FILES CHANGED BY PATCHING:
        total: 379

RPM CONFIGURATION FILES CHANGED BY PATCHING:
        total:  132

CONCLUSION:
        Something like 132/379 = 37.9% of the file changes to RPM are
        needed for OMA customization, and are not generally useful to
        RPM upstream.

Disclaimer:
        The statistics should be taken nominally: whether the actual result is 37.8% or even 25%
         doesn't change the conclusion.

You can avoid a _LOT_ of patching (and likely use GIT! GIT! GIT! instead of ancient CVS and patches)
if OMA creates a separate RPM configuration package and/or tarball.

(aside)
At one point in history, RPM was obligated to demonstrate _EXACTLY_ how RedHat built *.rpm
packages "reproducibly".  The status quo is considerably different in 2017: RPM supplies a
mechanism/framework for configuration, the actual configuration needs to be performed by
distributions, not by RPM itself.

Split all RPM configuration out of the rpm package (Y/n)?

**Comment by Conan-Kudo** [comment]
Yes, please. Let's split it out into an `rpm-openmandriva-setup` package. Merging everything into rpm has never been a good idea, and this rpm package itself is proof positive of why. If I remember correctly, Mandriva originally had the `rpm-mandriva-setup` package (which mimicked the `redhat-rpm-config` package in RH/Fedora).

[`rpm-mageia-setup`](http://svnweb.mageia.org/packages/cauldron/rpm-mageia-setup/current/SPECS/rpm-mageia-setup.spec?view=markup) (upstream project [rpm-setup](http://gitweb.mageia.org/software/rpm/rpm-setup/)) could be a helpful base to restoring the split.

**Comment by n3npq** [comment]
(aside)
Here is the contrarian opinion (and what was a design goal @rpm5.org circa 2009)

Most distros differ solely in macro dialect. RPM could easily handle loading different macro dialects so that, say, Fedorable packages could be built on Mandribble build systems and vice versa.

POK actually made huge progress isolating the peanut flavored M&M macro dialect into a single file (which is why a significant number of the file changes to "upstream" RPM are in macros/mandriva.in).

Meanwhile, no-one cared to participate in macro dialect unification and so casting seeds to the bistro winds (as suggested in this issue) is a pragmatic/realistic approach to getting customization out of RPM itself.

There are flaws -- including the need to build 2 packages, as well as retrofitting inheritance -- if all configuration is moved out of rpm itself. But flattening the 300+ patches in OMA are needed atm even if the original goal of handling macro dialects was also sane.

Meanwhile:
Split all RPM configuration out of the rpm package (Y/n)?

FWIW, macros were never intended to handle the current usage(s) ... a better RPM configuration paradigm is needed even if macros continue as a useful means to do templating.

**Comment by n3npq** [comment]
On #openmandriva-cooker, a separate package for RPM configuration seemed to have consensus.

I'll carry the existing patched RPM configuration (except for the per platform cpu-os.tar.gz changes) while upgrading until the new rpm configuration package is created.

**Comment by n3npq** [comment]
Here is the tarball of _ALL_ config and scripts extracted from these 2 binary packages:
`rpm-5.4.15-40-omv2015.0.x86_64.rpm 
rpm-build-5.4.15-40-omv2015.0.x86_64.rpm`

The tar ball can either be applied  to %buildroot in rpm.spec %install, or can be used to create a separate package for OMA customization of RPM.

Meanwhile I will be trimming all changes to scripts/* or macros/* files while dealing with the 300+ patches upgrading rpm-5.4.15 -> rpm-5.4.17 to reduce the complexity of reading patches.

[oma+rpm-config.tar.gz](https://github.com/OpenMandrivaAssociation/rpm/files/786156/oma.rpm-config.tar.gz)

**Comment by tpgxyz** [comment]
@n3npq Yes this is a good idea to keep configs into a separate package.

**Comment by berolinux** [comment]
Done
