### ISSUE TITLE
rpm-5.4.17 + omacoagulate patch

### ISSUE THREAD

**Issue by n3npq** [OpenMandrivaAssociation/rpm#9]
I have produced a coagulated patch (and tarball with the patch applied) that seems (imho) to be a "best effort" starting point for upgrading OMA rpm to 5.4.17 (or rpm-5.4.18).

All current OMA configuration customization has been captured (avoiding discussion of perhaps 1/3rd of the files patched in macros/* or scripts/*) from the OMA rpm/rpmbuild 5.4.15-30 binary rpm's. Obviously, if one chooses to untar the current configuration in %buildroot after building rpm there is very little risk of regression through misconfiguration.

Here is the current OMA configuration customization to RPM:
[oma+rpm-config.tar.gz](https://github.com/OpenMandrivaAssociation/rpm/files/788360/oma.rpm-config.tar.gz)

The patch applies cleanly to http://rpm5.org/files/rpm/rpm-5.4/rpm-5.4.17-0.20160512.src.rpm
as released.

Here is the patch:
[rpm+omacoagulate-5.4.17.tar.gz](https://github.com/OpenMandrivaAssociation/rpm/files/788359/rpm.omacoagulate-5.4.17.tar.gz)

Finally here is a "make dist" tarball of rpm-5.4.17 with the omacoagualate patch applied:
[rpm+omacoagulate-5.4.17.tar.gz](https://github.com/OpenMandrivaAssociation/rpm/files/788365/rpm.omacoagulate-5.4.17.tar.gz)

Q: Can we agree that the rpm+omacoagulate-5.4.17.tar.gz is an appropriate reference point for further discussion and starting actual regression testing?

**Comment by tpgxyz** [comment]
@n3npq Please correct me. I need to apply rpm+omacoagulate-5.4.17.tar.gz patch on current rpm git in openmandriva, right ?

What about to use pull requests ?

**Comment by n3npq** [comment]
The patch has already been applied in the tarball. I would use the tarball as a reference point while deciding on a much smaller set of "features", or whether rpm 5.4.18 is the desired endpoint.

Note that I have dropped a couple of "noisy" patches (like loadable embedded interpreters) in order to simplify rpm 5.4.17 ->5.4.18 through cvs upgrade. Those patches can easily be re-added (and I will do so), based on feedback.

But this issue is mostly coordinating a path forward: if you do not like what you see, then I need to hear about what else is needed. I believe a custom tarball with as many patches as can be simply applied, is the best way forward because of the complexity of discussing 300+ patches item by item.

**Comment by tpgxyz** [comment]
@n3npq Hi, finally i had some time to take a closer look on this.
Looks like you have pushed everything to one tarball. How i am suppose to update git repo, and remove already merged patches ? It is possible for you to prepare a pull request ?

**Comment by tpgxyz** [comment]
@n3npq Hi,
i've tried to catch you on irc because i've started to work on this. Unfortunately rpm.5.4.17-omacoagulate does not build.
Can you please help https://abf.openmandriva.org/build_lists/130518 ?
